version: '2'

services:
  badgeapp:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=sqlite:////opt/sqlite/db.sqlite3
      - WORKERS=1
      - LOG_FOLDER=/var/log/CLC
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CLC/logs:/var/log/CLC
      - .data/sqlite:/opt/sqlite
      - .:/opt/CLC:ro
    networks:
        default:
        internal:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/https.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/privkey.pem:/etc/nginx-keys/privkey.pem
      - ./conf/nginx/fullchain.pem:/etc/nginx-keys/fullchain.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - badgeapp

networks:
    default:
    internal:
        internal: true
